### PR TITLE
Provide remastered textures for .mag files to prevent magic effects from displaying broken SD textures.

### PR DESCRIPTION
**Pull request by Zurphing**
Currently, Form Rando provides .mag files to patch in to fix crashes when using magic on certain randomized forms without a 2nd keyblade. However, on PC, this causes broken looking effects for Fire, Firaga, Blizzard, Blizzara, and Blizzaga (Fira lacks remastered textures, so it remains fine). This PR provides the remastered textures to address this issue.

### CODE REVIEW

**Comment by Zurphing** [comment]
Note: Randomize.py was updated, but Randomize.exe & Anti_Wont_Replace_Base.exe need to be recompiled. Ran into issues on my end trying to compile them.

**Comment by shananas** [comment]
No need to provide the rematered assets just use and internal copy and a platform pc
- name: remastered\magic\BLIZZARD_1.mag\-0.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\BLIZZARD_1.mag\-0.dds
    type: internal
- name: remastered\magic\BLIZZARD_2.mag\-0.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\BLIZZARD_2.mag\-0.dds
    type: internal
- name: remastered\magic\BLIZZARD_2.mag\-1.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\BLIZZARD_2.mag\-1.dds
    type: internal
- name: remastered\magic\BLIZZARD_3.mag\-0.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\BLIZZARD_3.mag\-0.dds
    type: internal
- name: remastered\magic\BLIZZARD_3.mag\-1.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\BLIZZARD_3.mag\-1.dds
    type: internal
- name: remastered\magic\FIRE_1.mag\-0.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\FIRE_1.mag\-0.dds
    type: internal
- name: remastered\magic\FIRE_3.mag\-0.dds
  platform: pc
  method: copy
  source:
  - name: remastered\magic\FIRE_3.mag\-0.dds
    type: internal
    
after that ill have to ask @1234567890num to fix the exes with the proper changes to the exes for this

**Comment by Zurphing** [comment]
Updated to copy remastered textures internally on PC

**Comment by shananas** [comment]
Num wrote all his changes in his PR thanks for the quick fix and knowledge of it i wasnt sure why it was doing it since i thought the PC version still had the assets and didnt need to be provided again

**Pull request closed without merging**
